#!/bin/bash
# install hp scripting tools and change fan setting

STATUS=0
FAN_FILE=/tmp/fan-tweak.xml

# install
#yum install -y hp-scripting-tools
#STATUS=$(($STATUS || $?))

# create .xml file to change fan setting
cat << EOF > $FAN_FILE
<?xml version="1.0" encoding="UTF-8"?>
<!--generated by conrep version 4.5.0.0-->
<Conrep version="4.5.0.0" originating_platform="ProLiant DL60 Gen9" originating_family="U15" originating_romdate="12/27/2015" originating_processor_manufacturer="Intel(R) Corporation">

  <Section name="Thermal_Configuration" helptext="Selects the fan cooling solution for the system(not for ML350 G6).">Increased_Cooling</Section>

</Conrep>
EOF
STATUS=$(($STATUS || $?))

# run conrep to apply setting
/opt/hp/hp-scripting-tools/bin/conrep -x /opt/hp/hp-scripting-tools/etc/conrep.xml -l -f $FAN_FILE
STATUS=$(($STATUS || $?))

if [ "$STATUS" -eq 0 ]
then
	touch /root/.fan_config
fi
